/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  EventCriteria: { // input type
    address?: string | null; // String
    topic0?: string | null; // String
    topic1?: string | null; // String
    topic2?: string | null; // String
    topic3?: string | null; // String
    topic4?: string | null; // String
  }
  Range: { // input type
    from: number; // Int!
    to: number; // Int!
    unit: NexusGenEnums['Unit']; // Unit!
  }
  TransferCriteria: { // input type
    recipient?: string | null; // String
    sender?: string | null; // String
    txOrigin?: string | null; // String
  }
}

export interface NexusGenEnums {
  Order: "asc" | "desc"
  Unit: "block" | "time"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Account: { // root type
    authority?: NexusGenRootTypes['Authority'] | null; // Authority
    balance?: string | null; // String
    code?: string | null; // String
    deployer?: string | null; // String
    energy?: string | null; // String
    master?: string | null; // String
    sponsor?: string | null; // String
  }
  Authority: { // root type
    active: boolean; // Boolean!
    endorsor?: string | null; // String
    identity?: string | null; // String
    listed: boolean; // Boolean!
    signedBlockCount: string; // ID!
  }
  Block: { // root type
    beneficiary: string; // String!
    com: boolean; // Boolean!
    gasLimit: number; // Int!
    gasUsed: number; // Int!
    id: string; // String!
    isFinalized: boolean; // Boolean!
    isTrunk: boolean; // Boolean!
    number: number; // Int!
    parentID: string; // String!
    receiptsRoot: string; // String!
    signer: string; // String!
    size: number; // Int!
    stateRoot: string; // String!
    timestamp: number; // Int!
    totalScore: number; // Int!
    txsFeatures: number; // Int!
    txsRoot: string; // String!
  }
  Blocks: { // root type
    count: number; // Int!
    list: Array<NexusGenRootTypes['Block'] | null>; // [Block]!
  }
  Clause: { // root type
    data?: string | null; // String
    to?: string | null; // String
    value?: string | null; // String
  }
  Event: { // root type
    data: string; // String!
  }
  EventLog: { // root type
    data: string; // String!
  }
  EventLogs: { // root type
    count: number; // Int!
  }
  LogMeta: { // root type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    clauseIndex: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Outputs: { // root type
    events: NexusGenRootTypes['Event'][]; // [Event!]!
    transfers: NexusGenRootTypes['Transfer'][]; // [Transfer!]!
  }
  Query: {};
  Receipt: { // root type
    gasPayer: string; // String!
    gasUsed: number; // Int!
    paid: string; // String!
    reverted: boolean; // Boolean!
    reward: string; // String!
  }
  ReceiptMeta: { // root type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Transaction: { // root type
    blockID: string; // String!
    blockRef: string; // String!
    chainTag: number; // Int!
    delegator?: string | null; // String
    dependsOn?: string | null; // String
    expiration: number; // Int!
    gas: number; // Int!
    gasPriceCoef: number; // Int!
    id: string; // String!
    nonce: string; // String!
    origin: string; // String!
    size: number; // Int!
  }
  Transactions: { // root type
    count: number; // Int!
    list: Array<NexusGenRootTypes['Transaction'] | null>; // [Transaction]!
  }
  Transfer: { // root type
    amount: string; // String!
    recipient: string; // String!
    sender: string; // String!
  }
  TransferLogs: { // root type
    count: number; // Int!
  }
  TrasnferLog: { // root type
    amount: string; // String!
    recipient: string; // String!
    sender: string; // String!
  }
  TxMeta: { // root type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Account: { // field return type
    authority: NexusGenRootTypes['Authority'] | null; // Authority
    balance: string | null; // String
    code: string | null; // String
    deployer: string | null; // String
    energy: string | null; // String
    master: string | null; // String
    sponsor: string | null; // String
  }
  Authority: { // field return type
    active: boolean; // Boolean!
    endorsor: string | null; // String
    identity: string | null; // String
    listed: boolean; // Boolean!
    signedBlockCount: string; // ID!
  }
  Block: { // field return type
    beneficiary: string; // String!
    com: boolean; // Boolean!
    expendedTxs: NexusGenRootTypes['Transaction'][]; // [Transaction!]!
    gasLimit: number; // Int!
    gasUsed: number; // Int!
    id: string; // String!
    isFinalized: boolean; // Boolean!
    isTrunk: boolean; // Boolean!
    number: number; // Int!
    parentID: string; // String!
    receiptsRoot: string; // String!
    signer: string; // String!
    size: number; // Int!
    stateRoot: string; // String!
    timestamp: number; // Int!
    totalScore: number; // Int!
    transactions: string[]; // [String!]!
    txsFeatures: number; // Int!
    txsRoot: string; // String!
  }
  Blocks: { // field return type
    count: number; // Int!
    list: Array<NexusGenRootTypes['Block'] | null>; // [Block]!
  }
  Clause: { // field return type
    data: string | null; // String
    to: string | null; // String
    value: string | null; // String
  }
  Event: { // field return type
    address: string; // String!
    data: string; // String!
    topics: string[]; // [String!]!
  }
  EventLog: { // field return type
    address: string; // String!
    data: string; // String!
    meta: NexusGenRootTypes['LogMeta']; // LogMeta!
    topics: string[]; // [String!]!
  }
  EventLogs: { // field return type
    count: number; // Int!
    logs: NexusGenRootTypes['EventLog'][]; // [EventLog!]!
  }
  LogMeta: { // field return type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    clauseIndex: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Outputs: { // field return type
    contractAddress: string | null; // String
    events: NexusGenRootTypes['Event'][]; // [Event!]!
    transfers: NexusGenRootTypes['Transfer'][]; // [Transfer!]!
  }
  Query: { // field return type
    account: NexusGenRootTypes['Account'] | null; // Account
    block: NexusGenRootTypes['Block'] | null; // Block
    blocks: NexusGenRootTypes['Blocks'] | null; // Blocks
    events: NexusGenRootTypes['EventLogs']; // EventLogs!
    receipt: NexusGenRootTypes['Receipt'] | null; // Receipt
    transaction: NexusGenRootTypes['Transaction'] | null; // Transaction
    transactions: NexusGenRootTypes['Transactions']; // Transactions!
    transfers: NexusGenRootTypes['TransferLogs']; // TransferLogs!
  }
  Receipt: { // field return type
    gasPayer: string; // String!
    gasUsed: number; // Int!
    meta: NexusGenRootTypes['ReceiptMeta']; // ReceiptMeta!
    outputs: NexusGenRootTypes['Outputs'][]; // [Outputs!]!
    paid: string; // String!
    reverted: boolean; // Boolean!
    reward: string; // String!
  }
  ReceiptMeta: { // field return type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Transaction: { // field return type
    blockID: string; // String!
    blockRef: string; // String!
    chainTag: number; // Int!
    clauses: NexusGenRootTypes['Clause'][]; // [Clause!]!
    delegator: string | null; // String
    dependsOn: string | null; // String
    expiration: number; // Int!
    gas: number; // Int!
    gasPriceCoef: number; // Int!
    id: string; // String!
    meta: NexusGenRootTypes['TxMeta']; // TxMeta!
    nonce: string; // String!
    origin: string; // String!
    receipt: NexusGenRootTypes['Receipt'] | null; // Receipt
    size: number; // Int!
  }
  Transactions: { // field return type
    count: number; // Int!
    list: Array<NexusGenRootTypes['Transaction'] | null>; // [Transaction]!
  }
  Transfer: { // field return type
    amount: string; // String!
    recipient: string; // String!
    sender: string; // String!
  }
  TransferLogs: { // field return type
    count: number; // Int!
    logs: NexusGenRootTypes['TrasnferLog'][]; // [TrasnferLog!]!
  }
  TrasnferLog: { // field return type
    amount: string; // String!
    meta: NexusGenRootTypes['LogMeta']; // LogMeta!
    recipient: string; // String!
    sender: string; // String!
  }
  TxMeta: { // field return type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Account: { // field return type name
    authority: 'Authority'
    balance: 'String'
    code: 'String'
    deployer: 'String'
    energy: 'String'
    master: 'String'
    sponsor: 'String'
  }
  Authority: { // field return type name
    active: 'Boolean'
    endorsor: 'String'
    identity: 'String'
    listed: 'Boolean'
    signedBlockCount: 'ID'
  }
  Block: { // field return type name
    beneficiary: 'String'
    com: 'Boolean'
    expendedTxs: 'Transaction'
    gasLimit: 'Int'
    gasUsed: 'Int'
    id: 'String'
    isFinalized: 'Boolean'
    isTrunk: 'Boolean'
    number: 'Int'
    parentID: 'String'
    receiptsRoot: 'String'
    signer: 'String'
    size: 'Int'
    stateRoot: 'String'
    timestamp: 'Int'
    totalScore: 'Int'
    transactions: 'String'
    txsFeatures: 'Int'
    txsRoot: 'String'
  }
  Blocks: { // field return type name
    count: 'Int'
    list: 'Block'
  }
  Clause: { // field return type name
    data: 'String'
    to: 'String'
    value: 'String'
  }
  Event: { // field return type name
    address: 'String'
    data: 'String'
    topics: 'String'
  }
  EventLog: { // field return type name
    address: 'String'
    data: 'String'
    meta: 'LogMeta'
    topics: 'String'
  }
  EventLogs: { // field return type name
    count: 'Int'
    logs: 'EventLog'
  }
  LogMeta: { // field return type name
    blockID: 'String'
    blockNumber: 'Int'
    blockTimestamp: 'Int'
    clauseIndex: 'Int'
    txID: 'String'
    txIndex: 'ID'
    txOrigin: 'String'
  }
  Outputs: { // field return type name
    contractAddress: 'String'
    events: 'Event'
    transfers: 'Transfer'
  }
  Query: { // field return type name
    account: 'Account'
    block: 'Block'
    blocks: 'Blocks'
    events: 'EventLogs'
    receipt: 'Receipt'
    transaction: 'Transaction'
    transactions: 'Transactions'
    transfers: 'TransferLogs'
  }
  Receipt: { // field return type name
    gasPayer: 'String'
    gasUsed: 'Int'
    meta: 'ReceiptMeta'
    outputs: 'Outputs'
    paid: 'String'
    reverted: 'Boolean'
    reward: 'String'
  }
  ReceiptMeta: { // field return type name
    blockID: 'String'
    blockNumber: 'Int'
    blockTimestamp: 'Int'
    txID: 'String'
    txIndex: 'ID'
    txOrigin: 'String'
  }
  Transaction: { // field return type name
    blockID: 'String'
    blockRef: 'String'
    chainTag: 'Int'
    clauses: 'Clause'
    delegator: 'String'
    dependsOn: 'String'
    expiration: 'Int'
    gas: 'Int'
    gasPriceCoef: 'Int'
    id: 'String'
    meta: 'TxMeta'
    nonce: 'String'
    origin: 'String'
    receipt: 'Receipt'
    size: 'Int'
  }
  Transactions: { // field return type name
    count: 'Int'
    list: 'Transaction'
  }
  Transfer: { // field return type name
    amount: 'String'
    recipient: 'String'
    sender: 'String'
  }
  TransferLogs: { // field return type name
    count: 'Int'
    logs: 'TrasnferLog'
  }
  TrasnferLog: { // field return type name
    amount: 'String'
    meta: 'LogMeta'
    recipient: 'String'
    sender: 'String'
  }
  TxMeta: { // field return type name
    blockID: 'String'
    blockNumber: 'Int'
    blockTimestamp: 'Int'
  }
}

export interface NexusGenArgTypes {
  Query: {
    account: { // args
      address: string; // String!
    }
    block: { // args
      id: string; // String!
    }
    blocks: { // args
      order: NexusGenEnums['Order'] | null; // Order
      range?: NexusGenInputs['Range'] | null; // Range
      signer?: string | null; // String
      skip?: number | null; // Int
      take: number | null; // Int
    }
    events: { // args
      criterias?: Array<NexusGenInputs['EventCriteria'] | null> | null; // [EventCriteria]
      order: NexusGenEnums['Order'] | null; // Order
      range?: NexusGenInputs['Range'] | null; // Range
      skip?: number | null; // Int
      take: number | null; // Int
    }
    receipt: { // args
      id: string; // String!
    }
    transaction: { // args
      id: string; // String!
    }
    transactions: { // args
      order: NexusGenEnums['Order'] | null; // Order
      origin?: string | null; // String
      range?: NexusGenInputs['Range'] | null; // Range
      skip?: number | null; // Int
      take: number | null; // Int
    }
    transfers: { // args
      criterias?: Array<NexusGenInputs['TransferCriteria'] | null> | null; // [TransferCriteria]
      order: NexusGenEnums['Order'] | null; // Order
      range?: NexusGenInputs['Range'] | null; // Range
      skip?: number | null; // Int
      take: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}