/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  EventCriteria: { // input type
    address?: string | null; // String
    topic0?: string | null; // String
    topic1?: string | null; // String
    topic2?: string | null; // String
    topic3?: string | null; // String
    topic4?: string | null; // String
  }
  TransferCriteria: { // input type
    recipient?: string | null; // String
    sender?: string | null; // String
    txOrigin?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Block: { // root type
    beneficiary: string; // String!
    com: boolean; // Boolean!
    gasLimit: number; // Int!
    gasUsed: number; // Int!
    id: string; // String!
    isFinalized: boolean; // Boolean!
    isTrunk: boolean; // Boolean!
    number: number; // Int!
    parentID: string; // String!
    receiptsRoot: string; // String!
    signer: string; // String!
    size: number; // Int!
    stateRoot: string; // String!
    timestamp: number; // Int!
    totalScore: number; // Int!
    txsFeatures: number; // Int!
    txsRoot: string; // String!
  }
  Clause: { // root type
    data?: string | null; // String
    to?: string | null; // String
    value?: string | null; // String
  }
  Event: { // root type
    data: string; // String!
  }
  EventLog: { // root type
    data: string; // String!
  }
  EventLogs: { // root type
    count: number; // Int!
  }
  LogMeta: { // root type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    clauseIndex: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Outputs: { // root type
    events: NexusGenRootTypes['Event'][]; // [Event!]!
    transfers: NexusGenRootTypes['Transfer'][]; // [Transfer!]!
  }
  Query: {};
  Receipt: { // root type
    gasPayer: string; // String!
    gasUsed: number; // Int!
    paid: string; // String!
    reverted: boolean; // Boolean!
    reward: string; // String!
  }
  ReceiptMeta: { // root type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Transfer: { // root type
    amount: string; // String!
    recipient: string; // String!
    sender: string; // String!
  }
  TransferLogs: { // root type
    count: number; // Int!
  }
  TrasnferLog: { // root type
    amount: string; // String!
    recipient: string; // String!
    sender: string; // String!
  }
  Tx: { // root type
    blockID: string; // String!
    blockRef: string; // String!
    chainTag: number; // Int!
    delegator?: string | null; // String
    dependsOn?: string | null; // String
    expiration: number; // Int!
    gas: number; // Int!
    gasPriceCoef: number; // Int!
    id: string; // String!
    nonce: string; // String!
    origin: string; // String!
    size: number; // Int!
  }
  TxMeta: { // root type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Block: { // field return type
    beneficiary: string; // String!
    com: boolean; // Boolean!
    expendTxs: NexusGenRootTypes['Tx'][]; // [Tx!]!
    gasLimit: number; // Int!
    gasUsed: number; // Int!
    id: string; // String!
    isFinalized: boolean; // Boolean!
    isTrunk: boolean; // Boolean!
    number: number; // Int!
    parentID: string; // String!
    receiptsRoot: string; // String!
    signer: string; // String!
    size: number; // Int!
    stateRoot: string; // String!
    timestamp: number; // Int!
    totalScore: number; // Int!
    transactions: string[]; // [String!]!
    txsFeatures: number; // Int!
    txsRoot: string; // String!
  }
  Clause: { // field return type
    data: string | null; // String
    to: string | null; // String
    value: string | null; // String
  }
  Event: { // field return type
    address: string; // String!
    data: string; // String!
    topics: string[]; // [String!]!
  }
  EventLog: { // field return type
    address: string; // String!
    data: string; // String!
    meta: NexusGenRootTypes['LogMeta']; // LogMeta!
    topics: string[]; // [String!]!
  }
  EventLogs: { // field return type
    count: number; // Int!
    logs: NexusGenRootTypes['EventLog'][]; // [EventLog!]!
  }
  LogMeta: { // field return type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    clauseIndex: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Outputs: { // field return type
    contractAddress: string | null; // String
    events: NexusGenRootTypes['Event'][]; // [Event!]!
    transfers: NexusGenRootTypes['Transfer'][]; // [Transfer!]!
  }
  Query: { // field return type
    block: NexusGenRootTypes['Block'] | null; // Block
    events: NexusGenRootTypes['EventLogs']; // EventLogs!
    receipt: NexusGenRootTypes['Receipt'] | null; // Receipt
    transfers: NexusGenRootTypes['TransferLogs']; // TransferLogs!
    tx: NexusGenRootTypes['Tx'] | null; // Tx
  }
  Receipt: { // field return type
    gasPayer: string; // String!
    gasUsed: number; // Int!
    meta: NexusGenRootTypes['ReceiptMeta']; // ReceiptMeta!
    outputs: NexusGenRootTypes['Outputs'][]; // [Outputs!]!
    paid: string; // String!
    reverted: boolean; // Boolean!
    reward: string; // String!
  }
  ReceiptMeta: { // field return type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
    txID: string; // String!
    txIndex: string; // ID!
    txOrigin: string; // String!
  }
  Transfer: { // field return type
    amount: string; // String!
    recipient: string; // String!
    sender: string; // String!
  }
  TransferLogs: { // field return type
    count: number; // Int!
    logs: NexusGenRootTypes['TrasnferLog'][]; // [TrasnferLog!]!
  }
  TrasnferLog: { // field return type
    amount: string; // String!
    meta: NexusGenRootTypes['LogMeta']; // LogMeta!
    recipient: string; // String!
    sender: string; // String!
  }
  Tx: { // field return type
    blockID: string; // String!
    blockRef: string; // String!
    chainTag: number; // Int!
    clauses: NexusGenRootTypes['Clause'][]; // [Clause!]!
    delegator: string | null; // String
    dependsOn: string | null; // String
    expiration: number; // Int!
    gas: number; // Int!
    gasPriceCoef: number; // Int!
    id: string; // String!
    meta: NexusGenRootTypes['TxMeta']; // TxMeta!
    nonce: string; // String!
    origin: string; // String!
    receipt: NexusGenRootTypes['Receipt'] | null; // Receipt
    size: number; // Int!
  }
  TxMeta: { // field return type
    blockID: string; // String!
    blockNumber: number; // Int!
    blockTimestamp: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Block: { // field return type name
    beneficiary: 'String'
    com: 'Boolean'
    expendTxs: 'Tx'
    gasLimit: 'Int'
    gasUsed: 'Int'
    id: 'String'
    isFinalized: 'Boolean'
    isTrunk: 'Boolean'
    number: 'Int'
    parentID: 'String'
    receiptsRoot: 'String'
    signer: 'String'
    size: 'Int'
    stateRoot: 'String'
    timestamp: 'Int'
    totalScore: 'Int'
    transactions: 'String'
    txsFeatures: 'Int'
    txsRoot: 'String'
  }
  Clause: { // field return type name
    data: 'String'
    to: 'String'
    value: 'String'
  }
  Event: { // field return type name
    address: 'String'
    data: 'String'
    topics: 'String'
  }
  EventLog: { // field return type name
    address: 'String'
    data: 'String'
    meta: 'LogMeta'
    topics: 'String'
  }
  EventLogs: { // field return type name
    count: 'Int'
    logs: 'EventLog'
  }
  LogMeta: { // field return type name
    blockID: 'String'
    blockNumber: 'Int'
    blockTimestamp: 'Int'
    clauseIndex: 'Int'
    txID: 'String'
    txIndex: 'ID'
    txOrigin: 'String'
  }
  Outputs: { // field return type name
    contractAddress: 'String'
    events: 'Event'
    transfers: 'Transfer'
  }
  Query: { // field return type name
    block: 'Block'
    events: 'EventLogs'
    receipt: 'Receipt'
    transfers: 'TransferLogs'
    tx: 'Tx'
  }
  Receipt: { // field return type name
    gasPayer: 'String'
    gasUsed: 'Int'
    meta: 'ReceiptMeta'
    outputs: 'Outputs'
    paid: 'String'
    reverted: 'Boolean'
    reward: 'String'
  }
  ReceiptMeta: { // field return type name
    blockID: 'String'
    blockNumber: 'Int'
    blockTimestamp: 'Int'
    txID: 'String'
    txIndex: 'ID'
    txOrigin: 'String'
  }
  Transfer: { // field return type name
    amount: 'String'
    recipient: 'String'
    sender: 'String'
  }
  TransferLogs: { // field return type name
    count: 'Int'
    logs: 'TrasnferLog'
  }
  TrasnferLog: { // field return type name
    amount: 'String'
    meta: 'LogMeta'
    recipient: 'String'
    sender: 'String'
  }
  Tx: { // field return type name
    blockID: 'String'
    blockRef: 'String'
    chainTag: 'Int'
    clauses: 'Clause'
    delegator: 'String'
    dependsOn: 'String'
    expiration: 'Int'
    gas: 'Int'
    gasPriceCoef: 'Int'
    id: 'String'
    meta: 'TxMeta'
    nonce: 'String'
    origin: 'String'
    receipt: 'Receipt'
    size: 'Int'
  }
  TxMeta: { // field return type name
    blockID: 'String'
    blockNumber: 'Int'
    blockTimestamp: 'Int'
  }
}

export interface NexusGenArgTypes {
  Query: {
    block: { // args
      id: string; // String!
    }
    events: { // args
      criterias?: Array<NexusGenInputs['EventCriteria'] | null> | null; // [EventCriteria]
      skip?: number | null; // Int
      take?: number | null; // Int
    }
    receipt: { // args
      id: string; // String!
    }
    transfers: { // args
      criterias?: Array<NexusGenInputs['TransferCriteria'] | null> | null; // [TransferCriteria]
      skip?: number | null; // Int
      take?: number | null; // Int
    }
    tx: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}